### ISSUE TITLE
File staging

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/QCArchive#11]
QA would like to have RP to do staging of output files on an arbitrary location or, if possible, via MongoDB (see how FireWorks does it). Staging out onto a remote machine would be also a good option. A third option would be to use a REST interface to manage file staging (as QA does it at the moment).

**Comment by mturilli** [comment]
RADICAL is happy to use the REST interface. We would like to see the code of QA REST interface where data staging is handled.

**Comment by mturilli** [comment]
Andre to have a look at fireworks.

**Comment by dgasmith** [comment]
[This](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/queue/fireworks_adapter.py#L35) line tells Fireworks to store the result, which is then pulled out [here](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/queue/fireworks_adapter.py#L48).

**Comment by andre-merzky** [comment]
Thanks!

**Comment by mturilli** [comment]
Rutgers ready to support this. Will be coded once support for task has been developed.

**Comment by mturilli** [comment]
To be implemented after #8

**Comment by Lnaden** [comment]
~QCA will try to limit to about 10 tasks/second~

Redundant with comment below which is more detailed

**Comment by mturilli** [comment]
RP to stage out files to QCA. RADICAL to optimize output staging as done for input staging. Currently, we should limit output staging to around 10 tasks/s. Required by #13

**Comment by mturilli** [comment]
Json is enough and already supported.
