### ISSUE TITLE
Define use case for XRAC proposal

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/QCArchive#14]

**Comment by dgasmith** [comment]
If there a location and example that we should be basing the discussion here around? I have time to begin working on this, just not entirely sure it would be productive to start writing without some guidance.

**Comment by Lnaden** [comment]
Start by templating from the xrac tex files which already exist
Call the new file qcarchive.tex instead of "project8" or similar; place in 2019 folder
Recommended to look at "radical_extasy" as example (in 2018 folder)

**Comment by shantenujha** [comment]
Apologies, but not sure if this "ticket" is active (or not). Just checking that I'm not the stall point. Please let me know if I am..

**Comment by dgasmith** [comment]
This ticket is active. I am unfortunately quite overwhelmed with other QCA aspects at the moment. I will attempt to do this today.
