### ISSUE TITLE
Rest interface for RP

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/QCArchive#2]
This is the starting point: https://github.com/radical-cybertools/radical.nge

**Comment by mturilli** [comment]
Add JSON schema for the API

**Comment by mturilli** [comment]
Blocking #8

**Comment by andre-merzky** [comment]
Uh, I did something stupid: I went down the rabbit hole and looked for tolling support for REST API specification and documentation.  Most looks like overkill to me, really - but I started to use [apispec](https://dev.to/djiit/documenting-your-flask-powered-api-like-a-boss-9eo).  Its not ready, yet... :/

**Comment by mturilli** [comment]
Andre to report back about user experience with apispec. QCA to wait to see the quality of the generated documentation.

**Comment by mturilli** [comment]
We do not need it.
