### ISSUE TITLE
Use case document

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/QCArchive#3]

**Comment by dgasmith** [comment]
Do you have a template for this or should we start directly into it?

**Comment by mturilli** [comment]
We have a template for workflow descriptions. You can find it at: https://docs.google.com/document/d/1GQNSqXIBbV1FCGlEJCHBH9IY3BPozs3DCfELEO3ghcs/

If useful, we can use a different template for the software integration, following what I have already shared at: 
https://docs.google.com/document/d/1kXQofdkewBWJvJTVp9Bt09lo3sj706kFuBxkCjXIspc/

**Comment by dgasmith** [comment]
I have edited the template with several items. I would appreciate feedback as to the specificity of the wording.

**Comment by mturilli** [comment]
Thank you. I left some comments, @vivek-bala and @andre-merzky may want to add something.

**Comment by andre-merzky** [comment]
That document looks very useful to me!   I don't have comments on any specific items right now.

**Comment by mturilli** [comment]
Integrated the answers to the comments into the document. Note that staging in/out is required.

**Comment by mturilli** [comment]
0.1 version.
