### ISSUE TITLE
Requirement specification document

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/QCArchive#4]

**Comment by mturilli** [comment]
Add template of SRS

**Comment by mturilli** [comment]
https://docs.google.com/document/d/1bl5KGel9z3IwZxkbOGfHbGNX0jyajcD0Doc1hDL6zOM/edit

**Comment by sjayellis** [comment]
We have started filling in a draft version of the [SRS](https://drive.google.com/open?id=1gp2fohsmcwr6c9b6a47JnhJDUIKnGUsabJ01zFC2Wd8) with a focus on the integration between the two systems.

**Comment by mturilli** [comment]
RADICAL to comment and iterate

**Comment by mturilli** [comment]
@mturilli made a mistake. Iterate on the right document this time!

**Comment by Lnaden** [comment]
Link to doc will be added to README.md and will live permanently in the QCArchive/collaborations google drive
