### ISSUE TITLE
Provide information to deploy QCA server and rest interface

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/QCArchive#5]

**Comment by dgasmith** [comment]
A small run using the fireworks server can be found in the following [example](https://github.com/MolSSI/QCFractal/tree/master/examples/fireworks_server). Once we have the REST interface implemented we will provide another series of scripts to stand up a test server.

**Comment by mturilli** [comment]
Add a link to the current QCA REST interface

**Comment by dgasmith** [comment]
Relinking the PR here: MolSSI/QCFractal#72

We will look into writing an example which can spin up the above for experimentation purposes once it is merged.

**Comment by mturilli** [comment]
RADICAL ready to follow the example in the coming week

**Comment by vivek-bala** [comment]
I installed using the openff.yaml file and followed the qcarchive documentation for its installation.
I was able to start the mongodb and qcfractal servers successfully. 

Step 2 in fireworks_dataset example fails with 
```
$ python build_database.py 
Traceback (most recent call last):
  File "build_database.py", line 8, in <module>
    water_dimer = portal.data.get_molecule("water_dimer_minima.psimol")
  File "/home/vivek/Research/tools/miniconda2/envs/qcarxiv/lib/python3.6/site-packages/qcfractal/interface/data/data_getters.py", line 64, in get_molecule
    raise OSError("File: {}/{} not found".format("molecules", name))
OSError: File: molecules/water_dimer_minima.psimol not found
```

**Comment by dgasmith** [comment]
Yea, we missed that in our MANIFEST. I can fix it soon.

Can you `pip uninstall QCFractal; pip install -e .` while in the QCFractal base folder?

**Comment by vivek-bala** [comment]
Great, that fixed it. I was able to run through all the steps of the example. Thanks

**Comment by mturilli** [comment]
Ongoing.

**Comment by mturilli** [comment]
To be deployed on two.radical-project.

**Comment by mturilli** [comment]
Deployed on two.radical-project
